COMPONENT = HelloWorldAppC //define main component that program is based on.. compiler will look to the folder and picks this component where all wiring is done
include $(MAKERULES) //general tinyOS rules 

